#Sample single-stage MOBR pipeline for Cosmic Service


trigger: none

resources:
  repositories:
    - repository: GovernedTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

  pipelines:
  - pipeline: PrimaryArtifact
    source: "D2Services-CosmicPlatformTest-Windows-Official"
    branch: master

extends:
  template: v2/Microsoft.NonOfficial.yml@GovernedTemplates
  parameters:
    platform:
      name: m365
      serviceTreeId: "28a2529f-7085-4bbf-aa02-787135bb26a8"
      serviceGroupName: "Microsoft.M365.GriffinA.CosmicPlatformTest"    
    stages:
    - stage: 'PROD_CosmicSetup'
      variables:
        stage_type: nonDeployment
      displayName: 'CosmicSetup'
      jobs:
      - job: SetupCosmicPipelineVariables
        pool: 
          type: release
        steps:
          - download: PrimaryArtifact 
          - task: comic_deployment_priming_prod_with_onebranch@0
            name: SetVar
            inputs:
              DeploymentParamtersFilePath: <>
    
    - stage: 'Test_TestRingRelease'      
      displayName: 'Deploy service to TEST ring'
      dependsOn: PROD_CosmicSetup
      variables:
        stage_type: deployment
        azure_subscription_ids: "abcdef-1234-678a-h6duhw7hj56t"
        namespace_ring_json: <>
        SourceImages: <>
        CatalogHash: <>
        VersionToDeploy: <>
      jobs:
      - job: ReleaseJob
        pool:
          type: release
        steps:
          - download: PrimaryArtifact
          - task: prepare-deployment@1
            env:
              ServiceTreeId: <>
              ServiceGroupName: <>
            inputs:
              taskType: 'setupLockboxAuthzVariables'
          - task: ExpressV2Internal@1
            displayName: 'Ev2 Deploy'
            inputs:
              EndpointProviderType: 'LockboxService'
              ServiceRootPath: <>
              RolloutSpecPath: <>
              InlineDynamicBindingOverrides: <>
