#Sample single-stage MOBR pipeline for Cosmic Service


trigger: none

resources:
  repositories:
    - repository: GovernedTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

  pipelines:
  - pipeline: PrimaryArtifact
    source: <pipeline name>
    branch: master

extends:
  template: v2/Microsoft.Official.yml@GovernedTemplates
  parameters:
    platform:
      name: m365
      # The unique identifier for the service tree.
      serviceTreeId: "<service_tree_id>"
      serviceGroupName: "<service group name>"    
    stages:
    - stage: '<stage name>'     #this is always the first stage in COSMIC
      variables:
        stage_type: <stage type (enum)>
      displayName: '<stage display name>'
      jobs:
      - job: <name of the job>
        pool: 
          type: release
        steps:
          - download: <artifacts to be downloaded> 
          - task: <enum task name>
            name: SetVar
            inputs:
              DeploymentParamtersFilePath: '<file path>'

     # ***************************************TEST Ring deployment************************************************
    
    - stage: '<stage name>'      
      displayName: '<display name>'
      dependsOn: <depends on a previous stage>         #this stage depends on the cosmic setup stage
      variables:
        stage_type: <deployment / nonDeployment / registration>
        azure_subscription_ids: <GUID>
        namespace_ring_json: <>
        SourceImages: <>
        CatalogHash: <>
        VersionToDeploy: <>
      jobs:
      - job: ReleaseJob
        pool:
          type: release
        steps:
          - download: <artifacts to be deployed>
          - task: prepare-deployment@1      #mandatory task preceeding ExpressV2Internal task since the environment is TEST.
            env:
              ServiceTreeId: 28a2529f-7085-4bbf-aa02-787135bb26a8
              ServiceGroupName: Microsoft.M365.GriffinA.CosmicPlatformTest
            inputs:
              taskType: 'setupLockboxAuthzVariables'
          - task: ExpressV2Internal@1
            displayName: 'Ev2 Deploy'
            inputs:
              EndpointProviderType: 'LockboxService'
              ServiceRootPath: '$(PIPELINE.WORKSPACE)/PrimaryArtifact/drop_CosmicArtifact_CosmicArtifactJob/package/ModelService'
              RolloutSpecPath: '$(PIPELINE.WORKSPACE)/PrimaryArtifact/drop_CosmicArtifact_CosmicArtifactJob/package/ModelService/cosmicplatformtest-test-onebranch.rolloutspec.json'
              InlineDynamicBindingOverrides: <>

