#Sample single-stage MOBR definition for a Model D service
trigger: none

resources:
  repositories:
    - repository: GovernedTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
   

  pipelines:
  - pipeline: PrimaryArtifact
    source: "Nibiru_17.00.8433 Official" #The name of build pipeline producing artifacts
    branch: master

extends:
  template: v2/Microsoft.NonOfficial.yml@GovernedTemplates
  parameters:
    platform: 
      name: m365
      serviceTreeId: <GUID>
      serviceGroupName: <name of service group>    
    stages:
    
    #***************************************Deployment stage************************************************
    
    - stage: <stage>      
      displayName: 'display name'
      variables:
        stage_type: <deployment / nonDeployment / registration>
        azure_subscription_ids: <GUID>
      jobs:
      - job: ReleaseJob
        pool:
          type: release
        steps:
          - download: <artifacts to be downloaded>
          - task: <task name (enum)>
            inputs:
              dropMetadataContainerName: DropMetaData
              rootPaths: <relative path>
              destinationPath: <relative path>
              usePat: false
          - task: <task name (enum)>
            displayName: <string>
            inputs:
              EndpointProviderType: 'LockboxService'
              ServiceRootPath: <Artifacts folder path>
              RolloutSpecPath: <path to rolloutspec.json>
              InlineDynamicBindingOverrides: '{"scopeBindings":[{"scopeTagName":"GenevaIngestionPPE","bindings":[{"find":"__ENVIRONMENT__","replaceWith":"scucomplianceppe"},{"find":"__HostedServiceName__","replaceWith":"scucomplianceppe"}]}]}'                  


